# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 8564cb7b90636d430bac03fde2e6ebaa363df85335920d691c500ea8223f623225e84ac322d7c6e8e9eb89eb179caa3093d8bd178a46358706d2c7cc38ffe0dd

test:
  secret_key_base: 0babf218dbc9087ff5ecfe70300570d5e3dd65bc8f1a844d9edb499a7b12ad42b4827c61df2f8516f10a86db4914f1785ce67474771634b75fd67c4279bc2e07

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
